### ISSUE TITLE
Events page Related

### ISSUE THREAD

**Issue by actionjakson88** [drbenschmidt/dirtleague-discgolf#20]
Team,

When creating an event, and then adding in the CSV File.  I hit complete and the web page just greys all boxes.  It appears to work if I refresh the page manually.

**Comment by drbenschmidt** [comment]
Did you save before uploading? I'm not sure I intended for it to work on the same page as creating. I'm kinda surprised it worked after refreshing tbh

**Comment by actionjakson88** [comment]
There is no save button on it. After I upload the UDISC CSV. And then I hit complete. The page doesn't refresh automatically, or there isn't a progress bar. I have to manually refresh.

![image](https://user-images.githubusercontent.com/81534567/112856598-9298e880-9075-11eb-811d-994eebff1cf8.png)

**Comment by drbenschmidt** [comment]
I completed this a little while ago, it'll be visible in the next push to the `dev` server.
