### ISSUE TITLE
Editing an existing courses doesn't save properly

### ISSUE THREAD

**Issue by actionjakson88** [drbenschmidt/dirtleague-discgolf#27]
Clicking into Edit on Token Creek. ANd creating another layout then pressing submit doesn't save it.  Tested today  1:53pm utilizing chrome browser.

**Comment by actionjakson88** [comment]
Confirmed findings on Kyle's Pipes are clogged.

**Comment by drbenschmidt** [comment]
Good find! I'll be wrapping up model validation hopefully this weekend so there will be 1) feedback in the UI when something is wrong, and 2) I should notice it not working and fix it.

**Comment by drbenschmidt** [comment]
Checking the console for the network request, looks like it's not applying the `courseId` to the layout if it knows it, which means it probably isn't applying it when its an update request rather than a create.

**Comment by drbenschmidt** [comment]
Fixed, it'll be part of the next push to `dev`.
