### ISSUE TITLE
Upoading udisc CSV with no user's Fails

### ISSUE THREAD

**Issue by actionjakson88** [drbenschmidt/dirtleague-discgolf#39]
Dirt League,

Are we able to upload a CSV without user's specified. And have it to a local lookup on the user data base for the users and input the data?

<3

**Comment by drbenschmidt** [comment]
I'm not sure I understand what a CSV without users specified means. Are you talking about having a card without any players on it and having the uploaded CSV populate that data? If so, probably not since there isn't enough data in just the CSV's `name` column.

**Comment by actionjakson88** [comment]
No, if I don't specify the player within the website and just upload a
card. It doesn't automatically fit it to the alias's built to the website.

**Comment by drbenschmidt** [comment]
Oh! Ok, you're not authenticated and that action in the system requires authentication. I'll make sure that it's properly gated in the UI.
